name: growth_standards
description: A Dart implementation of various growth standards, WHO, CDC, Fenton, Intergrowth, etc.
version: 5.3.0
repository: https://github.com/devsdocs/growth_standards

environment:
  sdk: ^3.8.0

dependencies:
  clock: ^1.1.2
  dart_numerics: ^0.0.6
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  super_measurement: 5.0.0

dev_dependencies:
  build_runner: ^2.15.1
  freezed: ">=3.2.5 <5.0.0"
  json_serializable: ^6.14.0
  lint: ^2.8.0
  test: ^1.31.1
