name: who_growth_chart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0
  dart_numerics: ^0.0.6
  dio: ^5.8.0+1
  excel: ^4.0.6
  html: ^0.15.6
  reusable_tools: ^1.0.16
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.2.0
  test: ^1.24.0
